# Generated by Django 3.2.7 on 2021-10-11 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='LastName')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('frequencia_fisica', models.CharField(max_length=30, verbose_name='FrequenciaFisica')),
                ('objetivo_usuario', models.CharField(max_length=30, verbose_name='ObjetivoUsuario')),
                ('estatura', models.CharField(max_length=30, verbose_name='Estatura')),
                ('peso', models.IntegerField(default=0, verbose_name='Peso')),
                ('genero', models.CharField(max_length=30, verbose_name='Genero')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_nombre', models.CharField(max_length=30, verbose_name='planNombre')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.CharField(max_length=250, verbose_name='videoURL')),
                ('video_nombre', models.CharField(max_length=50, verbose_name='VideoNombre')),
                ('planes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='appTeamGym.planes')),
            ],
        ),
        migrations.CreateModel(
            name='Imc',
            fields=[
                ('imc_id', models.AutoField(primary_key=True, serialize=False)),
                ('imc_value', models.IntegerField(verbose_name='imcValue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='appTeamGym.planes'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
