# Generated by Django 3.2.7 on 2021-10-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTeamGym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso'),
        ),
    ]
